name: Clone and Push Wiki

on:
  push:
    branches:
      - main

jobs:
  clone-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      run: |
        git clone https://github.com/open-spaced-repetition/fsrs4anki.wiki.git source

    - name: Checkout target repository
      run: |
        git clone https://github.com/shigeyukey/fsrs4anki.wiki.git target
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Copy files
      run: |
        cp -r source/* target/

    - name: Commit and push changes
      run: |
        cd target
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Clone and push wiki"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}